# Generated by Django 5.2.12 on 2026-05-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_servicestyle_vip_price_servicestyleimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
