# Generated by Django 5.1.7 on 2025-04-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='is_paid',
            new_name='paid',
        ),
        migrations.AddField(
            model_name='appointment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
