# Generated by Django 5.1.7 on 2025-04-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_is_paid_appointment_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='paid',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='transaction_id',
        ),
    ]
